name: scirpy_integration
description: This module performs scTCR repertoire quality analysis and integration using scirpy on single-cell RNA-seq data stored in AnnData objects. It integrates VDJ and GEX data, incorporates various models to enhance data with additional metadata, and produces comprehensive visualizations, including UMAP plots and clonotype networks to display refined annotations and cell type distinctions.
keywords:
  - single-cell
  - TCR repertoire
  - scirpy
  - data visualization
tools:
  - quarto:
      description: Quarto is a scientific and technical publishing system built on Pandoc.
      homepage: https://quarto.org/
      documentation: https://quarto.org/docs/
      tool_dev_url: https://github.com/quarto-dev/quarto-cli
      licence: "GPL-3.0"
  - scanpy:
      description: Scanpy is a scalable toolkit for analyzing single-cell gene expression data.
      homepage: https://scanpy.readthedocs.io/
      documentation: https://scanpy.readthedocs.io/
      tool_dev_url: https://github.com/theislab/scanpy
  - scirpy:
      description: Scirpy is a Python library for analyzing single-cell T-cell receptor (TCR) data.
      homepage: https://icbi-lab.github.io/scirpy/
      documentation: https://icbi-lab.github.io/scirpy/
      tool_dev_url: https://github.com/icbi-lab/scirpy
  - pandas:
      description: Pandas is a powerful data analysis and manipulation library for Python.
      homepage: https://pandas.pydata.org/
      documentation: https://pandas.pydata.org/pandas-docs/stable/
      tool_dev_url: https://github.com/pandas-dev/pandas
  - numpy:
      description: NumPy is a fundamental package for scientific computing in Python.
      homepage: https://numpy.org/
      documentation: https://numpy.org/doc/
      tool_dev_url: https://github.com/numpy/numpy
  - seaborn:
      description: Seaborn is a Python visualization library based on matplotlib that provides a high-level interface for drawing attractive and informative statistical graphics.
      homepage: https://seaborn.pydata.org/
      documentation: https://seaborn.pydata.org/
      tool_dev_url: https://github.com/mwaskom/seaborn
  - mudata:
      description: MuData is a Python library for handling multimodal data structures.
      homepage: https://mudata.readthedocs.io/
      documentation: https://mudata.readthedocs.io/
      tool_dev_url: https://github.com/muon-scc/mudata
  - muon:
      description: Muon is a Python framework for multimodal single-cell data analysis.
      homepage: https://muon.readthedocs.io/
      documentation: https://muon.readthedocs.io/
      tool_dev_url: https://github.com/muons-multimodal/muon
  - matplotlib:
      description: Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.
      homepage: https://matplotlib.org/
      documentation: https://matplotlib.org/stable/contents.html
      tool_dev_url: https://github.com/matplotlib/matplotlib
input:
  - notebook:
      type: file
      description: Quarto notebook file (.qmd) that guides the TCR repertoire quality analysis.
      pattern: "*.qmd"
      parameters:
        project_name: "project"
        gex_anndata: "data/project_celltypist_annotation_object.h5ad"
        vdj_anndata: "data/project_tcr_repertoire_object.h5ad"
        clonotype_definition: "VDJ"
        distance_metric: "identity"
        sequence_type: "aa"
  - vdj_anndata:
      type: file
      description: AnnData object file containing VDJ data.
      pattern: "*.h5ad"
  - gex_anndata:
      type: file
      description: AnnData object file containing gene expression data.
      pattern: "*.h5ad"
  - config:
      type: file
      description: Configuration file that may contain additional settings or parameters for the notebook rendering.
      pattern: "*.{yml,yaml,json}"
output:
  - anndata:
      type: file
      description: Updated AnnData object with integrated GEX and TCR data.
      pattern: "data/${params.project_name}_gex_tcr_integration_object.h5mu"
  - html:
      type: file
      description: The rendered HTML report summarizing the TCR repertoire quality analysis.
      pattern: "report/${notebook.baseName}.html"
  - figures:
      type: directory
      description: Directory containing the generated figures from the notebook.
      pattern: "_freeze/**/figure-html/*.png"
authors:
  - Andre Fonseca (@oandrefonseca)
maintainers:
  - Andre Fonseca (@oandrefonseca)
